/**
 * Mock data for assetZ development — based on SOLLiD Cabinetry (SC) facility.
 * Swap these for real API calls as Grant's backend comes online.
 */

import type { Asset, Department, Facility } from '@/types'

export const MOCK_FACILITY: Facility = {
  id: 'fac-001',
  organization_id: 'org-solid',
  name: 'SOLLiD Cabinetry — Main Plant',
  building_code: 'B1',
  address: '123 Cabinet Way, Langley, BC',
  timezone: 'America/Vancouver',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
}

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 'dep-mil', organization_id: 'org-solid', facility_id: 'fac-001', name: 'Millwork',  code: 'MIL', created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: 'dep-fin', organization_id: 'org-solid', facility_id: 'fac-001', name: 'Finishing',  code: 'FIN', created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: 'dep-fac', organization_id: 'org-solid', facility_id: 'fac-001', name: 'Facilities', code: 'FAC', created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: 'dep-join', organization_id: 'org-solid', facility_id: 'fac-001', name: 'Joinery',   code: 'JOIN', created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
]

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'ast-001',
    organization_id: 'org-solid',
    facility_id: 'fac-001',
    department_id: 'dep-mil',
    facility_asset_id: 'SC-B1-MIL-EDGE-EDGE_BANDER-C1-01',
    asset_number: 'SLD-EB-0001',
    name: 'Edge Bander #1',
    description: 'Homag Edgeteq S-500 edge banding machine',
    manufacturer: 'Homag',
    model: 'Edgeteq S-500',
    serial_number: 'HMG-2019-44821',
    year_installed: 2019,
    company_code: 'SC',
    building_code: 'B1',
    department_code: 'MIL',
    system_type: 'EDGE',
    unit_type: 'EDGE_BANDER',
    dependency_code: 'C',
    dependency_group: 1,
    sequence: 1,
    status: 'operational',
    location_notes: 'West wall, Millwork bay A',
    feeds: ['ast-005'],
    created_at: '2024-01-15T08:00:00Z',
    updated_at: '2025-02-10T14:30:00Z',
  },
  {
    id: 'ast-002',
    organization_id: 'org-solid',
    facility_id: 'fac-001',
    department_id: 'dep-mil',
    facility_asset_id: 'SC-B1-MIL-CNC-ROVER-C2-01',
    asset_number: 'SLD-ROV-0001',
    name: 'Rover CNC #1',
    description: 'Biesse Rover A CNC machining center',
    manufacturer: 'Biesse',
    model: 'Rover A 1532',
    serial_number: 'BSS-2021-88231',
    year_installed: 2021,
    company_code: 'SC',
    building_code: 'B1',
    department_code: 'MIL',
    system_type: 'CNC',
    unit_type: 'ROVER',
    dependency_code: 'C',
    dependency_group: 2,
    sequence: 1,
    status: 'down',
    location_notes: 'Center of Millwork bay B',
    depends_on: ['ast-006'],
    created_at: '2024-02-01T08:00:00Z',
    updated_at: '2025-02-20T09:15:00Z',
  },
  {
    id: 'ast-003',
    organization_id: 'org-solid',
    facility_id: 'fac-001',
    department_id: 'dep-mil',
    facility_asset_id: 'SC-B1-MIL-CNC-SKILL-C3-01',
    asset_number: 'SLD-SKL-0001',
    name: 'Skill CNC Router #1',
    description: 'SCM Skill 1200 CNC router',
    manufacturer: 'SCM',
    model: 'Skill 1200',
    serial_number: 'SCM-2018-55102',
    year_installed: 2018,
    company_code: 'SC',
    building_code: 'B1',
    department_code: 'MIL',
    system_type: 'CNC',
    unit_type: 'SKILL',
    dependency_code: 'C',
    dependency_group: 3,
    sequence: 1,
    status: 'maintenance',
    location_notes: 'Millwork bay B, south end',
    depends_on: ['ast-006'],
    created_at: '2024-02-01T08:00:00Z',
    updated_at: '2025-02-18T16:00:00Z',
  },
  {
    id: 'ast-004',
    organization_id: 'org-solid',
    facility_id: 'fac-001',
    department_id: 'dep-mil',
    facility_asset_id: 'SC-B1-MIL-CNC-BEAM_SAW-C5-01',
    asset_number: 'SLD-BSW-0001',
    name: 'Beam Saw #1',
    description: 'Selco WNT 660 beam saw',
    manufacturer: 'Selco',
    model: 'WNT 660',
    serial_number: 'SLC-2020-77340',
    year_installed: 2020,
    company_code: 'SC',
    building_code: 'B1',
    department_code: 'MIL',
    system_type: 'CNC',
    unit_type: 'BEAM_SAW',
    dependency_code: 'C',
    dependency_group: 5,
    sequence: 1,
    status: 'operational',
    location_notes: 'Receiving end, Millwork bay A',
    feeds: ['ast-001', 'ast-002', 'ast-003'],
    created_at: '2024-03-01T08:00:00Z',
    updated_at: '2025-01-30T11:00:00Z',
  },
  {
    id: 'ast-005',
    organization_id: 'org-solid',
    facility_id: 'fac-001',
    department_id: 'dep-join',
    facility_asset_id: 'SC-B1-JOIN-JOIN-DOVETAILER-C6-01',
    asset_number: 'SLD-DVT-0001',
    name: 'Dovetailer #1',
    description: 'Casadei dovetail joinery machine',
    manufacturer: 'Casadei',
    model: 'DT-500',
    serial_number: 'CSD-2017-33901',
    year_installed: 2017,
    company_code: 'SC',
    building_code: 'B1',
    department_code: 'JOIN',
    system_type: 'JOIN',
    unit_type: 'DOVETAILER',
    dependency_code: 'C',
    dependency_group: 6,
    sequence: 1,
    status: 'operational',
    location_notes: 'Joinery bay',
    created_at: '2024-03-15T08:00:00Z',
    updated_at: '2025-02-01T09:00:00Z',
  },
  {
    id: 'ast-006',
    organization_id: 'org-solid',
    facility_id: 'fac-001',
    department_id: 'dep-fac',
    facility_asset_id: 'SC-B1-FAC-AIR-COMPRESSOR-U1-01',
    asset_number: 'SLD-CMP-0001',
    name: 'Air Compressor #1',
    description: 'Kaeser SK 25 rotary screw compressor',
    manufacturer: 'Kaeser',
    model: 'SK 25',
    serial_number: 'KSR-2016-12044',
    year_installed: 2016,
    company_code: 'SC',
    building_code: 'B1',
    department_code: 'FAC',
    system_type: 'AIR',
    unit_type: 'COMPRESSOR',
    dependency_code: 'U',
    dependency_group: 1,
    sequence: 1,
    status: 'operational',
    location_notes: 'Mechanical room, north end',
    dependents: ['ast-002', 'ast-003'],
    current_meter_value: 18420,
    meter_unit: 'hours',
    last_meter_update: '2025-02-20T08:00:00Z',
    created_at: '2024-01-01T08:00:00Z',
    updated_at: '2025-02-20T08:00:00Z',
  },
  {
    id: 'ast-007',
    organization_id: 'org-solid',
    facility_id: 'fac-001',
    department_id: 'dep-fin',
    facility_asset_id: 'SC-B1-FIN-SPRAY-AUTO_SPRAYBOOTH-C1-01',
    asset_number: 'SLD-SPB-0001',
    name: 'Auto Spray Booth #1',
    description: 'Giardina automated spray finishing system',
    manufacturer: 'Giardina',
    model: 'G-Tech 2000',
    serial_number: 'GRD-2022-90011',
    year_installed: 2022,
    company_code: 'SC',
    building_code: 'B1',
    department_code: 'FIN',
    system_type: 'SPRAY',
    unit_type: 'AUTO_SPRAYBOOTH',
    dependency_code: 'C',
    dependency_group: 1,
    sequence: 1,
    status: 'operational',
    location_notes: 'Finishing bay, east side',
    created_at: '2024-04-01T08:00:00Z',
    updated_at: '2025-02-15T10:30:00Z',
  },
]

/** Quick lookup by ID */
export function getMockAsset(id: string): Asset | undefined {
  return MOCK_ASSETS.find((a) => a.id === id)
}

/** Get asset by facility_asset_id */
export function getMockAssetByFacilityId(facilityAssetId: string): Asset | undefined {
  return MOCK_ASSETS.find((a) => a.facility_asset_id === facilityAssetId)
}
