import type { WorkRequest } from '@/types'

export const MOCK_REQUESTS: WorkRequest[] = [
  {
    id: 'req-001',
    organization_id: 'org-solid',
    requester_id: 'usr-tech6',
    requester_name: 'Mike Grimaldi',
    asset_id: 'ast-002',
    asset_identifier: 'SLD-ROV-0001',
    title: 'Rover CNC making loud grinding noise',
    description: 'During operation the spindle area makes a grinding/rattling sound, especially during rapid moves. Started this morning.',
    urgency: 'high',
    location_description: 'Mill Department, Grid C-5',
    status: 'submitted',
    queue_position: 1,
    notify_on_assignment: true,
    notify_on_completion: true,
    notify_on_queue_update: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-002',
    organization_id: 'org-solid',
    requester_id: 'usr-mgr2',
    requester_name: 'Braden Bond',
    title: 'Breakroom water fountain not working',
    description: 'No water coming out. Noticed it this morning.',
    urgency: 'low',
    location_description: 'Breakroom',
    status: 'submitted',
    queue_position: 3,
    notify_on_assignment: true,
    notify_on_completion: true,
    notify_on_queue_update: false,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'req-003',
    organization_id: 'org-solid',
    requester_id: 'usr-tech6',
    requester_name: 'Mike Grimaldi',
    asset_id: 'ast-001',
    asset_identifier: 'SLD-EB-0001',
    title: 'Edge bander glue pot temperature fluctuating',
    description: 'Temperature keeps dropping 10-15 degrees below setpoint. Causing weak glue joints.',
    urgency: 'normal',
    location_description: 'Mill Department, Grid D-3',
    status: 'approved',
    reviewed_by_id: 'usr-admin',
    reviewed_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    assigned_priority: 'high',
    assigned_tech_id: 'usr-tech3',
    work_order_id: 'wo-008',
    notify_on_assignment: true,
    notify_on_completion: true,
    notify_on_queue_update: false,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
]
