/**
 * Mock parts inventory for assetZ development — SOLLiD Cabinetry scenario.
 * Covers multiple asset types and all stock states.
 */

import type { Part, PartReservation } from '@/types'

export const MOCK_PARTS: Part[] = [
  {
    id: 'prt-001',
    organization_id: 'org-solid',
    part_number: 'HOM-250190',
    name: 'EB Feed Roller',
    description: 'Homag edge bander feed roller assembly — top roller replacement',
    manufacturer: 'Homag',
    vendor: 'Stiles Machinery',
    vendor_part_number: 'STL-250190',
    unit_of_measure: 'ea',
    unit_cost: 148.50,
    quantity_on_hand: 3,
    quantity_reserved: 1,
    reorder_point: 2,
    reorder_quantity: 4,
    status: 'in_stock',
    location: 'Shelf B3, Row 2',
    compatible_assets: ['ast-001'],
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },
  {
    id: 'prt-002',
    organization_id: 'org-solid',
    part_number: 'KAE-6.4404.0',
    name: 'Compressor Air Filter',
    description: 'Kaeser SK 25 intake air filter element',
    manufacturer: 'Kaeser',
    vendor: 'Compressor World',
    vendor_part_number: 'CW-64404',
    unit_of_measure: 'ea',
    unit_cost: 42.00,
    quantity_on_hand: 4,
    quantity_reserved: 0,
    reorder_point: 2,
    reorder_quantity: 6,
    status: 'in_stock',
    location: 'Shelf A1, Row 1',
    compatible_assets: ['ast-006'],
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'prt-003',
    organization_id: 'org-solid',
    part_number: 'KAE-6.3305.0',
    name: 'Compressor Oil 10L',
    description: 'Kaeser Sigma fluid compressor oil — 10 litre container',
    manufacturer: 'Kaeser',
    vendor: 'Compressor World',
    vendor_part_number: 'CW-63305',
    unit_of_measure: 'ea',
    unit_cost: 89.00,
    quantity_on_hand: 1,
    quantity_reserved: 1,
    reorder_point: 2,
    reorder_quantity: 4,
    status: 'out_of_stock',
    location: 'Shelf A1, Row 2',
    compatible_assets: ['ast-006'],
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-02-18T00:00:00Z',
  },
  {
    id: 'prt-004',
    organization_id: 'org-solid',
    part_number: 'BSS-F30-BELT',
    name: 'Rover Spindle V-Belt',
    description: 'Biesse Rover CNC spindle drive V-belt — F30 profile',
    manufacturer: 'Biesse',
    vendor: 'Stiles Machinery',
    vendor_part_number: 'STL-F30-BELT',
    unit_of_measure: 'ea',
    unit_cost: 62.00,
    quantity_on_hand: 0,
    quantity_reserved: 0,
    reorder_point: 2,
    reorder_quantity: 4,
    status: 'on_order',
    location: 'Shelf C2, Row 1',
    compatible_assets: ['ast-002'],
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-02-19T00:00:00Z',
  },
  {
    id: 'prt-005',
    organization_id: 'org-solid',
    part_number: 'HOM-G2700',
    name: 'EB Glue Adhesive 5kg',
    description: 'Homag Adhesive System G2700 EVA hot melt glue — 5kg block',
    manufacturer: 'Homag',
    vendor: 'Stiles Machinery',
    vendor_part_number: 'STL-G2700',
    unit_of_measure: 'ea',
    unit_cost: 38.50,
    quantity_on_hand: 6,
    quantity_reserved: 0,
    reorder_point: 3,
    reorder_quantity: 12,
    status: 'in_stock',
    location: 'Shelf B3, Row 1',
    compatible_assets: ['ast-001'],
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'prt-006',
    organization_id: 'org-solid',
    part_number: 'FAG-6205ZZ',
    name: 'Bearing 6205ZZ',
    description: 'FAG deep groove ball bearing 6205ZZ — 25×52×15mm, double shielded',
    manufacturer: 'FAG',
    vendor: 'Motion Industries',
    vendor_part_number: 'MOT-6205ZZ',
    unit_of_measure: 'ea',
    unit_cost: 14.75,
    quantity_on_hand: 8,
    quantity_reserved: 2,
    reorder_point: 4,
    reorder_quantity: 12,
    status: 'in_stock',
    location: 'Shelf D1, Row 3',
    compatible_assets: ['ast-001', 'ast-002', 'ast-003', 'ast-004'],
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-01-20T00:00:00Z',
  },
  {
    id: 'prt-007',
    organization_id: 'org-solid',
    part_number: 'HOM-250193',
    name: 'EB Scraper Blade',
    description: 'Homag edge bander scraper blade — trimming unit',
    manufacturer: 'Homag',
    vendor: 'Stiles Machinery',
    vendor_part_number: 'STL-250193',
    unit_of_measure: 'ea',
    unit_cost: 26.00,
    quantity_on_hand: 2,
    quantity_reserved: 0,
    reorder_point: 2,
    reorder_quantity: 6,
    status: 'low_stock',
    location: 'Shelf B3, Row 3',
    compatible_assets: ['ast-001'],
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
  },
  {
    id: 'prt-008',
    organization_id: 'org-solid',
    part_number: 'KAE-6.3540.0',
    name: 'Compressor V-Belt',
    description: 'Kaeser SK 25 main drive V-belt',
    manufacturer: 'Kaeser',
    vendor: 'Compressor World',
    vendor_part_number: 'CW-63540',
    unit_of_measure: 'ea',
    unit_cost: 55.00,
    quantity_on_hand: 2,
    quantity_reserved: 0,
    reorder_point: 1,
    reorder_quantity: 3,
    status: 'in_stock',
    location: 'Shelf A1, Row 3',
    compatible_assets: ['ast-006'],
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'prt-009',
    organization_id: 'org-solid',
    part_number: 'CAM-F24X24X2',
    name: 'Spray Booth Filter 24×24',
    description: 'Camfil intake filter panel 24×24×2 — MERV 8, spray booth intake',
    manufacturer: 'Camfil',
    vendor: 'Industrial Air Filtration',
    vendor_part_number: 'IAF-F24242',
    unit_of_measure: 'ea',
    unit_cost: 18.00,
    quantity_on_hand: 12,
    quantity_reserved: 3,
    reorder_point: 6,
    reorder_quantity: 24,
    status: 'in_stock',
    location: 'Shelf E2, Row 1',
    compatible_assets: ['ast-007'],
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-02-05T00:00:00Z',
  },
  {
    id: 'prt-010',
    organization_id: 'org-solid',
    part_number: 'IMS-ER32-10',
    name: 'CNC Collet ER32 10mm',
    description: 'ER32 precision collet 10mm — for CNC router tool holding',
    manufacturer: 'Iscar',
    vendor: 'MSC Industrial',
    vendor_part_number: 'MSC-ER32-10',
    unit_of_measure: 'ea',
    unit_cost: 32.00,
    quantity_on_hand: 0,
    quantity_reserved: 0,
    reorder_point: 3,
    reorder_quantity: 6,
    status: 'out_of_stock',
    location: 'Shelf C1, Row 2',
    compatible_assets: ['ast-002', 'ast-003'],
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
]

export const MOCK_PART_RESERVATIONS: PartReservation[] = [
  {
    id: 'res-001',
    part_id: 'prt-001',
    work_order_id: 'wo-002',
    quantity_reserved: 1,
    reserved_by_id: 'usr-tech1',
    reserved_at: '2026-02-21T08:00:00Z',
  },
  {
    id: 'res-002',
    part_id: 'prt-003',
    work_order_id: 'wo-004',
    quantity_reserved: 1,
    reserved_by_id: 'usr-mgr1',
    reserved_at: '2026-02-15T09:30:00Z',
  },
  {
    id: 'res-003',
    part_id: 'prt-006',
    work_order_id: 'wo-001',
    quantity_reserved: 2,
    reserved_by_id: 'usr-tech2',
    reserved_at: '2026-02-21T06:45:00Z',
  },
  {
    id: 'res-004',
    part_id: 'prt-009',
    work_order_id: 'wo-006',
    quantity_reserved: 3,
    reserved_by_id: 'usr-mgr1',
    reserved_at: '2026-02-19T11:00:00Z',
  },
]

/** Quick lookup by ID */
export function getMockPart(id: string): Part | undefined {
  return MOCK_PARTS.find((p) => p.id === id)
}
